// @generated by protoc-gen-connect-es v0.8.4 with parameter "target=ts"
// @generated from file v1/app_service.proto (package app.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetLockStateRequest, GetLockStateResponse, SetLockStateRequest, SetLockStateResponse } from "./app_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service app.v1.AppService
 */
export const AppService = {
  typeName: "app.v1.AppService",
  methods: {
    /**
     * @generated from rpc app.v1.AppService.GetLockState
     */
    getLockState: {
      name: "GetLockState",
      I: GetLockStateRequest,
      O: GetLockStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc app.v1.AppService.SetLockState
     */
    setLockState: {
      name: "SetLockState",
      I: SetLockStateRequest,
      O: SetLockStateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

