// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: v1/commands.proto

package bridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Csr []byte `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BridgeId string `protobuf:"bytes,1,opt,name=bridgeId,proto3" json:"bridgeId,omitempty"`
	Cert     []byte `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_commands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetBridgeId() string {
	if x != nil {
		return x.BridgeId
	}
	return ""
}

func (x *RegisterResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

type StreamCommandsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamCommandsRequest) Reset() {
	*x = StreamCommandsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_commands_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommandsRequest) ProtoMessage() {}

func (x *StreamCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commands_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommandsRequest.ProtoReflect.Descriptor instead.
func (*StreamCommandsRequest) Descriptor() ([]byte, []int) {
	return file_v1_commands_proto_rawDescGZIP(), []int{2}
}

// StreamCommand contains the type of command protobuf and the actual command protobuf as binary
type StreamCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Cmd  []byte `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
}

func (x *StreamCommand) Reset() {
	*x = StreamCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_commands_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommand) ProtoMessage() {}

func (x *StreamCommand) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commands_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommand.ProtoReflect.Descriptor instead.
func (*StreamCommand) Descriptor() ([]byte, []int) {
	return file_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *StreamCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamCommand) GetCmd() []byte {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type StreamCommand_EngageLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LockId string `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
}

func (x *StreamCommand_EngageLock) Reset() {
	*x = StreamCommand_EngageLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_commands_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamCommand_EngageLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommand_EngageLock) ProtoMessage() {}

func (x *StreamCommand_EngageLock) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commands_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommand_EngageLock.ProtoReflect.Descriptor instead.
func (*StreamCommand_EngageLock) Descriptor() ([]byte, []int) {
	return file_v1_commands_proto_rawDescGZIP(), []int{3, 0}
}

func (x *StreamCommand_EngageLock) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type StreamCommand_DisengageLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LockId string `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
}

func (x *StreamCommand_DisengageLock) Reset() {
	*x = StreamCommand_DisengageLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_commands_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamCommand_DisengageLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommand_DisengageLock) ProtoMessage() {}

func (x *StreamCommand_DisengageLock) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commands_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommand_DisengageLock.ProtoReflect.Descriptor instead.
func (*StreamCommand_DisengageLock) Descriptor() ([]byte, []int) {
	return file_v1_commands_proto_rawDescGZIP(), []int{3, 1}
}

func (x *StreamCommand_DisengageLock) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type StreamCommand_ReadLockState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LockId string `protobuf:"bytes,1,opt,name=lockId,proto3" json:"lockId,omitempty"`
}

func (x *StreamCommand_ReadLockState) Reset() {
	*x = StreamCommand_ReadLockState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_commands_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamCommand_ReadLockState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommand_ReadLockState) ProtoMessage() {}

func (x *StreamCommand_ReadLockState) ProtoReflect() protoreflect.Message {
	mi := &file_v1_commands_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommand_ReadLockState.ProtoReflect.Descriptor instead.
func (*StreamCommand_ReadLockState) Descriptor() ([]byte, []int) {
	return file_v1_commands_proto_rawDescGZIP(), []int{3, 2}
}

func (x *StreamCommand_ReadLockState) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

var File_v1_commands_proto protoreflect.FileDescriptor

var file_v1_commands_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x6b, 0x2e, 0x6e, 0x6f, 0x68, 0x6e, 0x73, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x0f, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x73, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x63, 0x73, 0x72, 0x22,
	0x42, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63,
	0x65, 0x72, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xad, 0x01, 0x0a,
	0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x63, 0x6d, 0x64, 0x1a, 0x24, 0x0a, 0x0a, 0x45, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x4c, 0x6f,
	0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x1a, 0x27, 0x0a, 0x0d, 0x44, 0x69,
	0x73, 0x65, 0x6e, 0x67, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x1a, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x4c, 0x6f, 0x63, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x32, 0xd5, 0x01, 0x0a,
	0x0a, 0x43, 0x6d, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x26, 0x2e, 0x64, 0x6b, 0x2e, 0x6e, 0x6f, 0x68,
	0x6e, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x64, 0x6b, 0x2e, 0x6e, 0x6f, 0x68, 0x6e, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x0e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x2c, 0x2e, 0x64,
	0x6b, 0x2e, 0x6e, 0x6f, 0x68, 0x6e, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x6b, 0x2e,
	0x6e, 0x6f, 0x68, 0x6e, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x68, 0x6e, 0x73, 0x2f, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x6b, 0x74, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_commands_proto_rawDescOnce sync.Once
	file_v1_commands_proto_rawDescData = file_v1_commands_proto_rawDesc
)

func file_v1_commands_proto_rawDescGZIP() []byte {
	file_v1_commands_proto_rawDescOnce.Do(func() {
		file_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_commands_proto_rawDescData)
	})
	return file_v1_commands_proto_rawDescData
}

var file_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_commands_proto_goTypes = []interface{}{
	(*RegisterRequest)(nil),             // 0: dk.nohns.cloud.bridge.RegisterRequest
	(*RegisterResponse)(nil),            // 1: dk.nohns.cloud.bridge.RegisterResponse
	(*StreamCommandsRequest)(nil),       // 2: dk.nohns.cloud.bridge.StreamCommandsRequest
	(*StreamCommand)(nil),               // 3: dk.nohns.cloud.bridge.StreamCommand
	(*StreamCommand_EngageLock)(nil),    // 4: dk.nohns.cloud.bridge.StreamCommand.EngageLock
	(*StreamCommand_DisengageLock)(nil), // 5: dk.nohns.cloud.bridge.StreamCommand.DisengageLock
	(*StreamCommand_ReadLockState)(nil), // 6: dk.nohns.cloud.bridge.StreamCommand.ReadLockState
}
var file_v1_commands_proto_depIdxs = []int32{
	0, // 0: dk.nohns.cloud.bridge.CmdService.Register:input_type -> dk.nohns.cloud.bridge.RegisterRequest
	2, // 1: dk.nohns.cloud.bridge.CmdService.StreamCommands:input_type -> dk.nohns.cloud.bridge.StreamCommandsRequest
	1, // 2: dk.nohns.cloud.bridge.CmdService.Register:output_type -> dk.nohns.cloud.bridge.RegisterResponse
	3, // 3: dk.nohns.cloud.bridge.CmdService.StreamCommands:output_type -> dk.nohns.cloud.bridge.StreamCommand
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_commands_proto_init() }
func file_v1_commands_proto_init() {
	if File_v1_commands_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_commands_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_commands_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamCommandsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_commands_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_commands_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamCommand_EngageLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_commands_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamCommand_DisengageLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_commands_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamCommand_ReadLockState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_commands_proto_goTypes,
		DependencyIndexes: file_v1_commands_proto_depIdxs,
		MessageInfos:      file_v1_commands_proto_msgTypes,
	}.Build()
	File_v1_commands_proto = out.File
	file_v1_commands_proto_rawDesc = nil
	file_v1_commands_proto_goTypes = nil
	file_v1_commands_proto_depIdxs = nil
}
