// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/lock_service.proto

package lockv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/nohns/proto/lock/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// LockServiceName is the fully-qualified name of the LockService service.
	LockServiceName = "lock.v1.LockService"
)

// LockServiceClient is a client for the lock.v1.LockService service.
type LockServiceClient interface {
	GetLockState(context.Context, *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error)
	SetLockState(context.Context, *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error)
}

// NewLockServiceClient constructs a client for the lock.v1.LockService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLockServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) LockServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &lockServiceClient{
		getLockState: connect_go.NewClient[v1.GetLockStateRequest, v1.GetLockStateResponse](
			httpClient,
			baseURL+"/lock.v1.LockService/GetLockState",
			opts...,
		),
		setLockState: connect_go.NewClient[v1.SetLockStateRequest, v1.SetLockStateResponse](
			httpClient,
			baseURL+"/lock.v1.LockService/SetLockState",
			opts...,
		),
	}
}

// lockServiceClient implements LockServiceClient.
type lockServiceClient struct {
	getLockState *connect_go.Client[v1.GetLockStateRequest, v1.GetLockStateResponse]
	setLockState *connect_go.Client[v1.SetLockStateRequest, v1.SetLockStateResponse]
}

// GetLockState calls lock.v1.LockService.GetLockState.
func (c *lockServiceClient) GetLockState(ctx context.Context, req *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error) {
	return c.getLockState.CallUnary(ctx, req)
}

// SetLockState calls lock.v1.LockService.SetLockState.
func (c *lockServiceClient) SetLockState(ctx context.Context, req *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error) {
	return c.setLockState.CallUnary(ctx, req)
}

// LockServiceHandler is an implementation of the lock.v1.LockService service.
type LockServiceHandler interface {
	GetLockState(context.Context, *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error)
	SetLockState(context.Context, *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error)
}

// NewLockServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLockServiceHandler(svc LockServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/lock.v1.LockService/GetLockState", connect_go.NewUnaryHandler(
		"/lock.v1.LockService/GetLockState",
		svc.GetLockState,
		opts...,
	))
	mux.Handle("/lock.v1.LockService/SetLockState", connect_go.NewUnaryHandler(
		"/lock.v1.LockService/SetLockState",
		svc.SetLockState,
		opts...,
	))
	return "/lock.v1.LockService/", mux
}

// UnimplementedLockServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLockServiceHandler struct{}

func (UnimplementedLockServiceHandler) GetLockState(context.Context, *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("lock.v1.LockService.GetLockState is not implemented"))
}

func (UnimplementedLockServiceHandler) SetLockState(context.Context, *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("lock.v1.LockService.SetLockState is not implemented"))
}
