// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/app_service.proto

package appv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/nohns/proto/app/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AppServiceName is the fully-qualified name of the AppService service.
	AppServiceName = "app.v1.AppService"
)

// AppServiceClient is a client for the app.v1.AppService service.
type AppServiceClient interface {
	GetLockState(context.Context, *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error)
	SetLockState(context.Context, *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error)
}

// NewAppServiceClient constructs a client for the app.v1.AppService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAppServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AppServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &appServiceClient{
		getLockState: connect_go.NewClient[v1.GetLockStateRequest, v1.GetLockStateResponse](
			httpClient,
			baseURL+"/app.v1.AppService/GetLockState",
			opts...,
		),
		setLockState: connect_go.NewClient[v1.SetLockStateRequest, v1.SetLockStateResponse](
			httpClient,
			baseURL+"/app.v1.AppService/SetLockState",
			opts...,
		),
	}
}

// appServiceClient implements AppServiceClient.
type appServiceClient struct {
	getLockState *connect_go.Client[v1.GetLockStateRequest, v1.GetLockStateResponse]
	setLockState *connect_go.Client[v1.SetLockStateRequest, v1.SetLockStateResponse]
}

// GetLockState calls app.v1.AppService.GetLockState.
func (c *appServiceClient) GetLockState(ctx context.Context, req *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error) {
	return c.getLockState.CallUnary(ctx, req)
}

// SetLockState calls app.v1.AppService.SetLockState.
func (c *appServiceClient) SetLockState(ctx context.Context, req *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error) {
	return c.setLockState.CallUnary(ctx, req)
}

// AppServiceHandler is an implementation of the app.v1.AppService service.
type AppServiceHandler interface {
	GetLockState(context.Context, *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error)
	SetLockState(context.Context, *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error)
}

// NewAppServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAppServiceHandler(svc AppServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/app.v1.AppService/GetLockState", connect_go.NewUnaryHandler(
		"/app.v1.AppService/GetLockState",
		svc.GetLockState,
		opts...,
	))
	mux.Handle("/app.v1.AppService/SetLockState", connect_go.NewUnaryHandler(
		"/app.v1.AppService/SetLockState",
		svc.SetLockState,
		opts...,
	))
	return "/app.v1.AppService/", mux
}

// UnimplementedAppServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAppServiceHandler struct{}

func (UnimplementedAppServiceHandler) GetLockState(context.Context, *connect_go.Request[v1.GetLockStateRequest]) (*connect_go.Response[v1.GetLockStateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("app.v1.AppService.GetLockState is not implemented"))
}

func (UnimplementedAppServiceHandler) SetLockState(context.Context, *connect_go.Request[v1.SetLockStateRequest]) (*connect_go.Response[v1.SetLockStateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("app.v1.AppService.SetLockState is not implemented"))
}
